# Generated by Django 4.0.5 on 2022-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Rating', models.IntegerField(default=0)),
                ('G_played', models.IntegerField(default=0)),
                ('G_won', models.IntegerField(default=0)),
                ('G_lost', models.IntegerField(default=0)),
            ],
        ),
    ]
