# Generated by Django 4.0.5 on 2022-07-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='Rating',
            field=models.IntegerField(default=1000),
        ),
    ]
