# Generated by Django 4.0.5 on 2022-07-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_playerdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerdata',
            options={'ordering': ['-Rating']},
        ),
    ]
